name: cicd

on: [push]

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - run: python helloworld.py
    
  build:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/upload-artifact@v2
        with:
          name: helloworld
          path: .
          
      - name: Replace Strings
        shell: pwsh
        run: |
          Get-Content $GITHUB_PATH/test
  
